apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-dbconnect
  labels:
    heptio.com/example: lamp
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: php-dbconnect
  template:
    metadata:
      labels:
        app: php-dbconnect
    spec:
      containers:
      - image: sunithaar/tamilphp:latest
        imagePullPolicy: Always
        name: php-dbconnect
        resources:
          requests:
            cpu: 70m
            memory: 0.2Gi
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
          - name: MYSQL_HOST
            value: mysql.default.svc.cluster.local
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    "heptio.com/example": lamp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  type: NodePort   
  selector:
    app: php-dbconnect
  type: LoadBalancer
